apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admissioncontroller
webhooks:
  - name: admissioncontroller.dwpbank.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    failurePolicy: Ignore
    clientConfig:
      service:
        name: admissioncontroller
        namespace: default
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXRENDQWtBQ0NRQ0RvTVU3S0REeE9UQU5CZ2txaGtpRzl3MEJBUXNGQURCdU1Rc3dDUVlEVlFRR0V3SkUKUlRFU01CQUdBMVVFQnd3SlJuSmhibXRtZFhKME1RMHdDd1lEVlFRS0RBUmhZMjFsTVFzd0NRWURWUVFMREFKdgpaREVMTUFrR0ExVUVBd3dDWTJFeElqQWdCZ2txaGtpRzl3MEJDUUVXRTNsdmRYSmxiV0ZwYkVCbmJXRnBiQzVqCmIyMHdIaGNOTVRneE1qSTVNRGN4T0RFM1doY05NakV4TWpJNE1EY3hPREUzV2pCdU1Rc3dDUVlEVlFRR0V3SkUKUlRFU01CQUdBMVVFQnd3SlJuSmhibXRtZFhKME1RMHdDd1lEVlFRS0RBUmhZMjFsTVFzd0NRWURWUVFMREFKdgpaREVMTUFrR0ExVUVBd3dDWTJFeElqQWdCZ2txaGtpRzl3MEJDUUVXRTNsdmRYSmxiV0ZwYkVCbmJXRnBiQzVqCmIyMHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEVDNFTWFXWnFzM2R1cFpodzYKN2FTYVJ3czlnNXpNdmtYUVluRk1XRUloU1ZScm8wRzZwZ0QxY1ZJY1BIYmN4OEljckhqcDdvQVgvdUJ1WFo2MQp5REd0OFNudGlzSlZuSEFGVzVBeWJIT1I2R1dVZEZoaHc2RHNXY2dPa3pqV09aYXRUcnM0ZkxFay9OVEdWbjROCnl4QWs0UWllY0pIWDhmcCsrbEdSNXBYVnpVZitueWxCK2dYb0pmOEowWnN0d3hKYTdJNlhLaExhRnEyMDFBK2QKbFBQTTU0SWsvbTVrSTFuWU53UWljZ0plMzRROG41SklwbWpPdUZwL01mQ2lSd0IyMm80WGY1bndjdlNXbXowYgpWRFBZVWlJMjZTRk1IZnV5aDFpeU1MeHdyeDhaSWtXSXJBOTZNdkUxcXhIek9xTDd2bGpjalBaUS9zWUg5UVIvClRHZE5BZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHejV6bitpMHhnTGdtenNnTlcza3I1NHY1TFUKV0Z3QUd6MGY1d0FpRWNEUnl3RFZNWjVPTWtqd01vaFNJamZheG8wRWF3WVFpdVYwRDhNSWhYYmVvWDRuRStUeQp6a3FpMHFkcVVWUGVtRzFGMEwwZmhWY05IeUZnZkVzTFMxTk55S0ZlTHFEUEpFTmpPb2FnbTVteFVPNU5ET0txCmZOMDJ4MFVyemk1R1hVK05XTHM5UmFGeXJhRm9iaG1hSitNVXV5TFZtWDU1blhGSXNsdkZzRmJGS3ZDWis3VGIKWVN4VlVVbkZPWjA4VHBkazhqQVdFTWl1c0ZNN3M0aWZIRzFhMmpWczJhOEZrcUNzL2ZRcGRycklYQ05hQS9XdwpjcnNoMFBadm5WRWNHeWJkaUV0TDhtcUpqMDlZSHVGck9mNWp5T2ZYTW9ZUnlvMjk0Y1NUamw2Rkl1dz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
